<?php

$manifest = array (
    'acceptable_sugar_versions' => 
        array (
            'regex_matches' => array (
                '6\.[2-9].*', '7\..*',
            ),
        ),
    'acceptable_sugar_flavors' =>
        array(
            'CE','PRO','ENT','CORP','ULT'
        ),
    'key'=>'jjwg',
    'author' => 'Jeff Walters',
    'description' => 'JJWDesign Google Maps v2.1.8 for SugarCRM v6.2+',
    'icon' => 'images/default/images/icon_jjwg_Maps.gif',
    'is_uninstallable' => true,
    'name' => 'JJWDesign_Google_Maps',
    'published_date' => '2013-11-20 12:12:12',
    'type' => 'module',
    'version' => '2.1.8-6.2+',
    'remove_tables' => 'prompt'
);


$installdefs = array (
  'id' => 'Google_Maps_20131120',

  'beans' => 
  array (
    array (
      'module' => 'jjwg_Maps',
      'class' => 'jjwg_Maps',
      'path' => 'modules/jjwg_Maps/jjwg_Maps.php',
      'tab' => true,
    ),
    array (
      'module' => 'jjwg_Markers',
      'class' => 'jjwg_Markers',
      'path' => 'modules/jjwg_Markers/jjwg_Markers.php',
      'tab' => true,
    ),
    array (
      'module' => 'jjwg_Areas',
      'class' => 'jjwg_Areas',
      'path' => 'modules/jjwg_Areas/jjwg_Areas.php',
      'tab' => true,
    ),
    array (
      'module' => 'jjwg_Address_Cache',
      'class' => 'jjwg_Address_Cache',
      'path' => 'modules/jjwg_Address_Cache/jjwg_Address_Cache.php',
      'tab' => true,
    ),
  ),

  'layoutdefs' => 
  array (
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
  ),

  'relationships' => 
  array (
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/jjwg_maps_jjwg_areasMetaData.php',
    ),
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/jjwg_maps_jjwg_markersMetaData.php',
    ),
  ),

  // Images copied to the custom/themes/default/images folder
  'image_dir' => '<basepath>/images',

  'administration' => 
  array(
    array(
      'from' => '<basepath>/SugarModules/modules/Administration/jjwg_Mapsadmin.php',
    ),
  ),

  'copy' => 
  array (
    // jjwg_Maps Module (views, images, javascript and tpls)
    array (
      'from' => '<basepath>/SugarModules/modules/jjwg_Maps',
      'to' => 'modules/jjwg_Maps',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/jjwg_Markers',
      'to' => 'modules/jjwg_Markers',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/jjwg_Areas',
      'to' => 'modules/jjwg_Areas',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/jjwg_Address_Cache',
      'to' => 'modules/jjwg_Address_Cache',
    ),

    // Accounts - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Accounts/views/view.list.php',
      'to' => 'custom/modules/Accounts/views/view.list.php',
    ),
    // Accounts - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Accounts/AccountsListViewSmarty.php',
      'to' => 'custom/modules/Accounts/AccountsListViewSmarty.php',
    ),
    // Accounts - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
    ),

    // Cases - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Cases/views/view.list.php',
      'to' => 'custom/modules/Cases/views/view.list.php',
    ),
    // Cases - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Cases/CasesListViewSmarty.php',
      'to' => 'custom/modules/Cases/CasesListViewSmarty.php',
    ),
    // Cases - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
    ),

    // Contacts - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Contacts/views/view.list.php',
      'to' => 'custom/modules/Contacts/views/view.list.php',
    ),
    // Contacts - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Contacts/ContactsListViewSmarty.php',
      'to' => 'custom/modules/Contacts/ContactsListViewSmarty.php',
    ),
    // Contacts - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
    ),

    // Leads - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Leads/views/view.list.php',
      'to' => 'custom/modules/Leads/views/view.list.php',
    ),
    // Leads - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Leads/LeadsListViewSmarty.php',
      'to' => 'custom/modules/Leads/LeadsListViewSmarty.php',
    ),
    // Leads - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
    ),

    // Meetings - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Meetings/views/view.list.php',
      'to' => 'custom/modules/Meetings/views/view.list.php',
    ),
    // Meetings - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Meetings/MeetingsListViewSmarty.php',
      'to' => 'custom/modules/Meetings/MeetingsListViewSmarty.php',
    ),
    // Meetings - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Meetings/MeetingsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Meetings/MeetingsJjwg_MapsLogicHook.php',
    ),

    // Opportunities - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Opportunities/views/view.list.php',
      'to' => 'custom/modules/Opportunities/views/view.list.php',
    ),
    // Opportunities - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Opportunities/OpportunitiesListViewSmarty.php',
      'to' => 'custom/modules/Opportunities/OpportunitiesListViewSmarty.php',
    ),
    // Opportunities - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
    ),

    // Project - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Project/views/view.list.php',
      'to' => 'custom/modules/Project/views/view.list.php',
    ),
    // Project - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Project/ProjectListViewSmarty.php',
      'to' => 'custom/modules/Project/ProjectListViewSmarty.php',
    ),
    // Project - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
    ),

    // Prospects - Extend List View
    array (
      'from' => '<basepath>/custom/modules/Prospects/views/view.list.php',
      'to' => 'custom/modules/Prospects/views/view.list.php',
    ),
    // Prospects - Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Prospects/ProspectsListViewSmarty.php',
      'to' => 'custom/modules/Prospects/ProspectsListViewSmarty.php',
    ),
    // Prospects - Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Prospects/ProspectsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Prospects/ProspectsJjwg_MapsLogicHook.php',
    ),

  ),

  'custom_fields' => 
  array (
    'Accountsjjwg_maps_lng_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Accountsjjwg_maps_lat_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Accountsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Accountsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Accountsjjwg_maps_address_c' => 
    array (
      'id' => 'Accountsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Casesjjwg_maps_lng_c' => 
    array (
      'id' => 'Casesjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Cases',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Casesjjwg_maps_lat_c' => 
    array (
      'id' => 'Casesjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Cases',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Casesjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Casesjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Casesjjwg_maps_address_c' => 
    array (
      'id' => 'Casesjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Contactsjjwg_maps_lng_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Contactsjjwg_maps_lat_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Contactsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Contactsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Contactsjjwg_maps_address_c' => 
    array (
      'id' => 'Contactsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Leadsjjwg_maps_lng_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Leadsjjwg_maps_lat_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Leadsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Leadsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Leadsjjwg_maps_address_c' => 
    array (
      'id' => 'Leadsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Meetingsjjwg_maps_lng_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Meetingsjjwg_maps_lat_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Meetings',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Meetingsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2012-08-17 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Meetingsjjwg_maps_address_c' => 
    array (
      'id' => 'Meetingsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Meetings',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Opportunitiesjjwg_maps_lng_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Opportunities',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Opportunitiesjjwg_maps_lat_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Opportunities',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Opportunitiesjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Opportunities',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Opportunitiesjjwg_maps_address_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Opportunities',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Projectjjwg_maps_lng_c' => 
    array (
      'id' => 'Projectjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Projectjjwg_maps_lat_c' => 
    array (
      'id' => 'Projectjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Projectjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Projectjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Projectjjwg_maps_address_c' => 
    array (
      'id' => 'Projectjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Prospectsjjwg_maps_lng_c' => 
    array (
      'id' => 'Prospectsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Prospects',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Prospectsjjwg_maps_lat_c' => 
    array (
      'id' => 'Prospectsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Prospects',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
    ),
    'Prospectsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Prospectsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Prospects',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
    'Prospectsjjwg_maps_address_c' => 
    array (
      'id' => 'Prospectsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Prospects',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2012-08-17 22:06:01',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
    ),
  ),

  'language' => 
  array (

    // Administrative Language
    array (
      'from' => '<basepath>/SugarModules/modules/Administration/language/en_us.lang.php',
      'to_module' => 'Administration',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/Administration/language/es_es.lang.php',
      'to_module' => 'Administration',
      'language' => 'es_es',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/Administration/language/ge_ge.lang.php',
      'to_module' => 'Administration',
      'language' => 'ge_ge',
    ),
    array (
      'from' => '<basepath>/SugarModules/modules/Administration/language/pt_br.lang.php',
      'to_module' => 'Administration',
      'language' => 'pt_br',
    ),

    // Relationships Language
    array (
      'from' => '<basepath>/SugarModules/relationships/language/en_us.jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/es_es.jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
      'language' => 'es_es',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ge_ge.jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
      'language' => 'ge_ge',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pt_br.jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
      'language' => 'pt_br',
    ),
    
    array (
      'from' => '<basepath>/SugarModules/relationships/language/en_us.jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/es_es.jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
      'language' => 'es_es',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ge_ge.jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
      'language' => 'ge_ge',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pt_br.jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
      'language' => 'pt_br',
    ),
    
    array (
      'from' => '<basepath>/SugarModules/relationships/language/en_us.jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/es_es.jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'es_es',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/ge_ge.jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'ge_ge',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pt_br.jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
      'language' => 'pt_br',
    ),

    // Application Language
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    array (
      'from' => '<basepath>/SugarModules/language/application/es_es.lang.php',
      'to_module' => 'application',
      'language' => 'es_es',
    ),
    array (
      'from' => '<basepath>/SugarModules/language/application/ge_ge.lang.php',
      'to_module' => 'application',
      'language' => 'ge_ge',
    ),
    array (
      'from' => '<basepath>/SugarModules/language/application/pt_br.lang.php',
      'to_module' => 'application',
      'language' => 'pt_br',
    ),
  ),

  'vardefs' => 
  array (
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/jjwg_Areas.php',
      'to_module' => 'jjwg_Areas',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/jjwg_Markers.php',
      'to_module' => 'jjwg_Markers',
    ),
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/jjwg_Maps.php',
      'to_module' => 'jjwg_Maps',
    ),
  ),

  'logic_hooks' => array(

     // Prospects
     array(
        'module'         => 'Prospects',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Prospects/ProspectsJjwg_MapsLogicHook.php',
        'class'          => 'ProspectsJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Prospects',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Prospects/ProspectsJjwg_MapsLogicHook.php',
        'class'          => 'ProspectsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),

     // Leads
     array(
        'module'         => 'Leads',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
        'class'          => 'LeadsJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Leads',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
        'class'          => 'LeadsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),

     // Contacts
     array(
        'module'         => 'Contacts',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
        'class'          => 'ContactsJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Contacts',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
        'class'          => 'ContactsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),

     // Meetings
     array(
        'module'         => 'Meetings',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateMeetingGeocodeInfo',
        'file'           => 'custom/modules/Meetings/MeetingsJjwg_MapsLogicHook.php',
        'class'          => 'MeetingsJjwg_MapsLogicHook',
        'function'       => 'updateMeetingGeocodeInfo',
     ),

     // Opportunities (5 hooks)
     array(
        'module'         => 'Opportunities',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
        'class'          => 'OpportunitiesJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Opportunities',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
        'class'          => 'OpportunitiesJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),
     array(
        'module'         => 'Opportunities',
        'hook'           => 'after_save',
        'order'          => 78,
        'description'    => 'updateRelatedProjectGeocodeInfo',
        'file'           => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
        'class'          => 'OpportunitiesJjwg_MapsLogicHook',
        'function'       => 'updateRelatedProjectGeocodeInfo',
     ),
     array(
        'module'         => 'Opportunities',
        'hook'           => 'after_relationship_add',
        'order'          => 77,
        'description'    => 'addRelationship',
        'file'           => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
        'class'          => 'OpportunitiesJjwg_MapsLogicHook',
        'function'       => 'addRelationship',
     ),
     array(
        'module'         => 'Opportunities',
        'hook'           => 'after_relationship_delete',
        'order'          => 77,
        'description'    => 'deleteRelationship',
        'file'           => 'custom/modules/Opportunities/OpportunitiesJjwg_MapsLogicHook.php',
        'class'          => 'OpportunitiesJjwg_MapsLogicHook',
        'function'       => 'deleteRelationship',
     ),

     // Cases (4 Hooks)
     array(
        'module'         => 'Cases',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
        'class'          => 'CasesJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Cases',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
        'class'          => 'CasesJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),
     array(
        'module'         => 'Cases',
        'hook'           => 'after_relationship_add',
        'order'          => 77,
        'description'    => 'addRelationship',
        'file'           => 'custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
        'class'          => 'CasesJjwg_MapsLogicHook',
        'function'       => 'addRelationship',
     ),
     array(
        'module'         => 'Cases',
        'hook'           => 'after_relationship_delete',
        'order'          => 77,
        'description'    => 'deleteRelationship',
        'file'           => 'custom/modules/Cases/CasesJjwg_MapsLogicHook.php',
        'class'          => 'CasesJjwg_MapsLogicHook',
        'function'       => 'deleteRelationship',
     ),

     // Project (4 Hooks)
     array(
        'module'         => 'Project',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
        'class'          => 'ProjectJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Project',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
        'class'          => 'ProjectJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),
     array(
        'module'         => 'Project',
        'hook'           => 'after_relationship_add',
        'order'          => 77,
        'description'    => 'addRelationship',
        'file'           => 'custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
        'class'          => 'ProjectJjwg_MapsLogicHook',
        'function'       => 'addRelationship',
     ),
     array(
        'module'         => 'Project',
        'hook'           => 'after_relationship_delete',
        'order'          => 77,
        'description'    => 'deleteRelationship',
        'file'           => 'custom/modules/Project/ProjectJjwg_MapsLogicHook.php',
        'class'          => 'ProjectJjwg_MapsLogicHook',
        'function'       => 'deleteRelationship',
     ),

     // Accounts (7 hooks)
     array(
        'module'         => 'Accounts',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'updateGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'updateGeocodeInfo',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_save',
        'order'          => 77,
        'description'    => 'updateRelatedMeetingsGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedMeetingsGeocodeInfo',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_save',
        'order'          => 78,
        'description'    => 'updateRelatedProjectGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedProjectGeocodeInfo',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_save',
        'order'          => 79,
        'description'    => 'updateRelatedOpportunitiesGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedOpportunitiesGeocodeInfo',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_save',
        'order'          => 80,
        'description'    => 'updateRelatedCasesGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'updateRelatedCasesGeocodeInfo',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_relationship_add',
        'order'          => 77,
        'description'    => 'addRelationship',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'addRelationship',
     ),
     array(
        'module'         => 'Accounts',
        'hook'           => 'after_relationship_delete',
        'order'          => 77,
        'description'    => 'deleteRelationship',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'deleteRelationship',
     ),

   ), 

);

