<?php

$manifest = array (
     'acceptable_sugar_versions' => 
	  array (
		'regex_matches' => array (
			'6\..*',
		),
      ),
      'acceptable_sugar_flavors' =>
      array(
        'CE', 'PRO','ENT'
      ),
      'key'=>'jjwg',
      'author' => 'Jeff Walters',
      'description' => 'JJWDesign Google Maps v1.2 for SugarCRM v6.0+',
      'icon' => 'icons/default/icon_jjwg_Maps.gif',
      'is_uninstallable' => true,
      'name' => 'JJWDesign_Google_Maps',
      'published_date' => '2010-11-13 17:41:01',
      'type' => 'module',
      'version' => '1.2-6.0+',
      'remove_tables' => 'prompt',
);

$installdefs = array (
  'id' => 'Google_Maps',
  'beans' => 
  array (
    array (
      'module' => 'jjwg_Maps',
      'class' => 'jjwg_Maps',
      'path' => 'modules/jjwg_Maps/jjwg_Maps.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',

  'copy' => 
  array (
    // jjwg_Maps Module (views, images, javascript and tpls)
    array (
      'from' => '<basepath>/SugarModules/modules/jjwg_Maps',
      'to' => 'modules/jjwg_Maps',
    ),

    // Controller Entry Point Registry
    // See post_install.php script

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Accounts/views/view.list.php',
      'to' => 'custom/modules/Accounts/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Accounts/AccountsListViewSmarty.php',
      'to' => 'custom/modules/Accounts/AccountsListViewSmarty.php',
    ),
    // Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
    ),

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Cases/views/view.list.php',
      'to' => 'custom/modules/Cases/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Cases/CasesListViewSmarty.php',
      'to' => 'custom/modules/Cases/CasesListViewSmarty.php',
    ),

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Contacts/views/view.list.php',
      'to' => 'custom/modules/Contacts/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Contacts/ContactsListViewSmarty.php',
      'to' => 'custom/modules/Contacts/ContactsListViewSmarty.php',
    ),
    // Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
    ),

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Leads/views/view.list.php',
      'to' => 'custom/modules/Leads/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Leads/LeadsListViewSmarty.php',
      'to' => 'custom/modules/Leads/LeadsListViewSmarty.php',
    ),
    // Logic Hook
    array (
      'from' => '<basepath>/custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
      'to' => 'custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
    ),

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Opportunities/views/view.list.php',
      'to' => 'custom/modules/Opportunities/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Opportunities/OpportunitiesListViewSmarty.php',
      'to' => 'custom/modules/Opportunities/OpportunitiesListViewSmarty.php',
    ),

    // Extend List View 
    array (
      'from' => '<basepath>/custom/modules/Project/views/view.list.php',
      'to' => 'custom/modules/Project/views/view.list.php',
    ),
    // Extend List View Smarty
    array (
      'from' => '<basepath>/custom/modules/Project/ProjectListViewSmarty.php',
      'to' => 'custom/modules/Project/ProjectListViewSmarty.php',
    ),

  ),

  'custom_fields' => 
  array (
    'Accountsjjwg_maps_lng_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsjjwg_maps_lat_c' => 
    array (
      'id' => 'Accountsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Accounts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Accountsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsjjwg_maps_address_c' => 
    array (
      'id' => 'Accountsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Casesjjwg_maps_lng_c' => 
    array (
      'id' => 'Casesjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Cases',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Casesjjwg_maps_lat_c' => 
    array (
      'id' => 'Casesjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Cases',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Casesjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Casesjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Casesjjwg_maps_address_c' => 
    array (
      'id' => 'Casesjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Cases',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsjjwg_maps_lng_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsjjwg_maps_lat_c' => 
    array (
      'id' => 'Contactsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Contacts',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Contactsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Contactsjjwg_maps_address_c' => 
    array (
      'id' => 'Contactsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Contacts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsjjwg_maps_lat_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsjjwg_maps_lng_c' => 
    array (
      'id' => 'Leadsjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Leads',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Leadsjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Leadsjjwg_maps_address_c' => 
    array (
      'id' => 'Leadsjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Leads',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Opportunitiesjjwg_maps_lng_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Opportunities',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Opportunitiesjjwg_maps_lat_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Opportunities',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Opportunitiesjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Opportunities',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Opportunitiesjjwg_maps_address_c' => 
    array (
      'id' => 'Opportunitiesjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Opportunities',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_lat_c' => 
    array (
      'id' => 'Projectjjwg_maps_lat_c',
      'name' => 'jjwg_maps_lat_c',
      'label' => 'LBL_JJWG_MAPS_LAT',
      'comments' => NULL,
      'help' => 'Latitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '10',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'precision' => '8',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_lng_c' => 
    array (
      'id' => 'Projectjjwg_maps_lng_c',
      'name' => 'jjwg_maps_lng_c',
      'label' => 'LBL_JJWG_MAPS_LNG',
      'comments' => NULL,
      'help' => 'Longitude',
      'module' => 'Project',
      'type' => 'float',
      'max_size' => '11',
      'require_option' => '0',
      'default' => '0.00000000',
      'default_value' => '0.00000000',
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '8',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_geocode_status_c' => 
    array (
      'id' => 'Projectjjwg_maps_geocode_status_c',
      'name' => 'jjwg_maps_geocode_status_c',
      'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
      'comments' => 'Geocode Status',
      'help' => 'Geocode Status',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Projectjjwg_maps_address_c' => 
    array (
      'id' => 'Projectjjwg_maps_address_c',
      'name' => 'jjwg_maps_address_c',
      'label' => 'LBL_JJWG_MAPS_ADDRESS',
      'comments' => 'Address',
      'help' => 'Address',
      'module' => 'Project',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default' => NULL,
      'default_value' => NULL,
      'date_modified' => '2010-09-18 22:06:01',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    // 10/05/2010 - Removed parent_name, parent_type and parent_id fields
    // See the jjwg_Maps module module vardefs.php instead!
  ),

  'language' => array (
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),

  'logic_hooks' => array(
     array(
        'module'         => 'Accounts',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'removeGeocodeInfo',
        'file'           => 'custom/modules/Accounts/AccountsJjwg_MapsLogicHook.php',
        'class'          => 'AccountsJjwg_MapsLogicHook',
        'function'       => 'removeGeocodeInfo',
     ), 
     array(
        'module'         => 'Contacts',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'removeGeocodeInfo',
        'file'           => 'custom/modules/Contacts/ContactsJjwg_MapsLogicHook.php',
        'class'          => 'ContactsJjwg_MapsLogicHook',
        'function'       => 'removeGeocodeInfo',
     ), 
     array(
        'module'         => 'Leads',
        'hook'           => 'before_save',
        'order'          => 77,
        'description'    => 'removeGeocodeInfo',
        'file'           => 'custom/modules/Leads/LeadsJjwg_MapsLogicHook.php',
        'class'          => 'LeadsJjwg_MapsLogicHook',
        'function'       => 'removeGeocodeInfo',
     ), 
   ), 

);





